#! /bin/sh

export XDG_CURRENT_DESKTOP="i3"
/usr/libexec/gsd-xsettings &
xsetroot -cursor_name left_ptr
wmname LG3D
sxhkd &
variety &
$HOME/.config/polybar/launch.sh
compton -b
fcitx -r

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
