#! /bin/sh

$HOME/.config/polybar/launch.sh
# export XDG_CURRENT_DESKTOP="i3"
xsetroot -cursor_name left_ptr
wmname LG3D
sxhkd &
variety &
picom --experimental-backends -b
fcitx -r

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Blender desktop='^8' follow=on
bspc rule -a jetbrains-idea desktop='^2'state=floating follow=on
bspc rule -a qq desktop='^5'state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a latte-dock floating=on

