#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) loginctl lock-session ;;
                *Logout) loginctl kill-user `whoami`;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
